#!/bin/bash


echo "
The purpose of these tests is to test a few modules with the environment
close to production environment as much as possible

In many cases, the input files are likely to be huge and are excluded from
application package. So please be awared if the errors said some files
are missing
" 1>&2


python -tt -m unittest discover -v -p prodtest*.py
